name: MasterDeployCI
on:
  push:
    branches:
      - feature-ci-cd
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email lucas2005gao@gmail.com
          git config --global user.name lucas2005gao
          git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/lucas2005gao/assignment1.git
          npm run deploy
